export const constants = {
  CLIENT_ID: "Client id:",
  TOTAL_BIO_LINK_USERS: "Total Bio Users",
  TODAYS_BIO_LINK_USERS: "Today's Bio Users",
  SECRET_ID: "Client secret:",
  CHANGE_IT: "Change it",
  DASHBOARD: "Web dashboard",
  LINK_BIO: "Link bio",
  ONLY_DASHBOARD: "Dashboard",
  API_KEY: "API Key",
  SR_NO: "SR NO.",
  NAME: "Name",
  FULL_NAME: "Full name",
  EMAIL: "Email",
  TOTAL_URLS: "Total links",
  STATUS: "Status",
  DETAILS: "Details",
  SHORT_URL: "Short link",
  CLICKS: "Clicks",
  CLICKS_SMALL: "clicks",
  SORRY: "Sorry!",
  NO_LINKS_FOUND: "No links found",
  NO_DATA_FOUND: "No data found",
  ALL: "All",
  VIEW_ALL: "View All",
  VIEW: "See more",
  TOTAL_ORDERS: "Total Orders",
  TODAYS_ORDERS: "Today's Orders",
  TOTAL_EARNINGS: "Total Earning",
  TWO_DAYS_EARNINGS: "2D Earning",
  THIRTY_DAYS_EARNINGS: "30D Earning",
};
