export const errorConst = {
  // ? SUCCESS
  LINK_COPIED: "Link copied successfully",
  USER_STATUS_CHANGED: "User status changed successfully",
  USER_BACK_TO_DEFAULT: "Users Default Package Activated successfully",
  PROFILE_UPDATED: "Profile Updated Successfully",
  RESELLER_ADDED: "Reseller Added successfully",
  SSL_ADDED: "SSL Added successfully",

  BLOCKED_DOMAIN_STATUS: "Domain status changed successfully",
  LINK_SHORT_SUCCESSFULLY: "Link shorten successfully",
  LINK_EDITED_SUCCESSFULLY: "Shorten link edited successfully",

  // ? ERROR
  URL_NOT_VALID: "URL is not valid",
  ALIAS_LENGTH: "Alias length must be at least 4 characters",
  ALIAS_MAX_LENGTH: "Alias length should not be greater than 50 characters",
  UPDATE_USER_STATUS_WARNING:
    "Are you sure you want to change this user's status?",
  COMPANY_NAME: "Company name must be greater than 1 character",
  COMPANY_NAME_MAX_LENGTH: "Company name should be less than 25 characters",
  LAST_NAME_LENGTH: "Lastname length must be greater than 1 character",
  LAST_NAME_MAX_LENGTH: "Last name should not be greater than 20 characters",
  FIRST_NAME_SPACE: "Spaces are not allowed in first name",
  LAST_NAME_SPACE: "Spaces are not allowed in last name",
  NEW_PASSWORD_REQUIRED: "New Password is required",
  CONFIRM_PASSWORD_REQUIRED: "Confirm Password is required",
  OLD_PASSWORD_REQUIRED: "Old Password is required",
  PASSWORD_LENGTH: "Password must be at least 8 character",
  CONFIRM_PASSWORD_NOT_MATCH:
    "Confirm Password does not matched with new Password",
  ENTER_RESELLER_LIMIT: "Enter Reseller Limit",
  RESELLER_LIMIT: "Reseller Limit must be greater than and equals 1",
  RESELLER_UP_LIMIT: "Reseller Limit must be less than and equals 1000",
  ENTER_SSL_LIMIT: "Enter SSL Certificate Limit",
  SSL_LIMIT: "SSL Certificate Limit must be greater than and equals 1",
  SSL_UP_LIMIT: "SSL Certificate Limit must be less than and equals 1000",
  ARE_YOU_SURE_COUPON: "Are you sure you want to delete this coupon?",
  ARE_YOU_SURE_DEFAULT: "Are you sure you want to activate default package?",
  NEW_PASSWORD: "Your new password should be different from old password",
  ENTER_LINK: "Please enter link",
  LINK_NOT_VALID: "Link is not valid",
  SPACES_NOT_ALLOWED: "Spaces are not allowed",
  SPECIAL_NOT_ALLOWED: "Special characters are not allowed",
  EXPIRATION_LINK_REQUIRED: "Expiration link is required",
  CLICK_REQUIRED: "Clicks is required",
  EXPIRATION_LINK_NOT_VALID: "Expiration link is not valid",
  UTM_MEDIUM_REQUIRED: "UTM medium is required",
  UTM_CAMPAIGN_REQUIRED: "UTM campaign is required",
  UTM_SOURCE_REQUIRED: "UTM source is required",
  YOU_DONT_HAVE_SERVICE: "You don't have this service",
  SOMETHING_WENT_WRONG: "Something went wrong",
  EXPIRE_DURATION: "Duration must be a number",
  DURATION_REQUIRED: "Duration is required",
  DURATION_GREATER_THAN_0: "Duration must be greater than 0",
  DURATION_LESS_THAN_365: "Duration must be less than 365 days",
  DURATION_LESS_THAN_12: "Duration must be less than 12 months",
  EXPIRATION_UPDATED: "Auto expiration link setting updated successfully",
  DELETION_UPDATED: "Auto deletion link setting updated successfully",
  TELEGRAM_SETTING_UPDATED:
    "Telegram notification settings updated successfully",
  API_KEY_STATUS: "User API Key Status changed successfully",
  DELETE_API_KEY: "Usre API Key deleted successfully",
};
