export const placeholderConst = {
  ENTER_FIRST_NAME: "Enter first name",
  ENTER_LAST_NAME: "Enter last name",
  ENTER_OLD_PASSWORD: "Enter old password",
  ENTER_NEW_PASSWORD: "Enter new password",
  ENTER_CONFIRM_PASSWORD: "Enter confirm password",
  ENTER_RESELLER_LIMIT: "Enter reseller limit",
  ENTER_SSL_LIMIT: "Enter SSL Certificate limit",
  TYPE_LINK: "Type or paste your link",
  ENTER_ALIAS: "Enter alias",
  ENTER_PASSWORD: "Enter password",
  ENTER_EXPIRATION_LINK: "Enter expiration link",
  ENTER_EXPIRATION_DATE: "Enter expiration date",
  ENTER_TOTAL_CLICKS: "Enter total clicks",
  ENTER_NOTE: "Enter note",
  ENTER_CUSTOM_CODE: "Enter custom code",
  ENTER_UTM_SOURCE: "Enter utm source",
  ENTER_UTM_MEDIUM: "Enter utm medium",
  ENTER_UTM_CAMPAIGN: "Enter utm campaign",
  SEARCH: "Search by link, original link",
  SELECT_DOMAIN: "Select domain",
  SELECT_SPACE: "Select space",
  ENTER_CLICKS: "Enter clicks",
  ENTER_DURATION: "Enter duration",
  ENTER_DURATION_TYPE: "Enter duration type",
  COUPON_NAME: "Enter coupon name",
  REFERENCE_NAME: "Enter reference name",
  NUMBER_OF_COUPON: "Enter number of coupon",
  HELP_CENTER: "Enter help center link",
  SYSTEM_DOMAIN: "Enter system domain redirection link",
  USER_DOMAIN: "Enter user domain redirection link",
};
